apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sftpgo-db-secret
spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: sftpgo-db-secret
    creationPolicy: Owner
  data:
    - secretKey: dbProvider
      remoteRef:
        key: {{ .Values.secrets.db }}
        property: provider
    - secretKey: dbHost
      remoteRef:
        key: {{ .Values.secrets.db }}
        property: host
    - secretKey: dbPort
      remoteRef:
        key: {{ .Values.secrets.db }}
        property: port
    - secretKey: dbUsername
      remoteRef:
        key: {{ .Values.secrets.db }}
        property: username
    - secretKey: dbPassword
      remoteRef:
        key: {{ .Values.secrets.db }}
        property: password
    - secretKey: dbName
      remoteRef:
        key: {{ .Values.secrets.db }}
        property: name
  